In [1]:
from load_data import DataLoader
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd
from scipy.stats import wilcoxon, binomtest, spearmanr, gaussian_kde, kurtosis, skew, chi2_contingency

In [2]:
loader = DataLoader()
loader.load_data()
df = loader.data
df_questionnaire = loader.questionnaire
df_questionnaire_preferences = loader.questionnaire_preferences

In [3]:
def perform_t_test(result, matrix_len, value_map):
    R = np.zeros((1, matrix_len))
    for key, value in value_map.items():
        R[0, result.model.exog_names.index(key)] = value
    display(result.t_test(R))

**MODELS**

In [4]:
model_trade_off = smf.mixedlm(
    "log_c ~ log_d * camera", 
    data=df, 
    groups=df["participant"], 
    re_formula="~camera"
)

result_trade_off = model_trade_off.fit() 
print(result_trade_off.summary())

                     Mixed Linear Model Regression Results
===============================================================================
Model:                    MixedLM         Dependent Variable:         log_c
No. Observations:         830             Method:                     REML
No. Groups:               30              Scale:                      0.0805
Min. group size:          26              Log-Likelihood:             -199.2068
Max. group size:          28              Converged:                  Yes
Mean group size:          27.7
-------------------------------------------------------------------------------
                                     Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                             2.646    0.159 16.610 0.000  2.334  2.959
camera[T.stationary_cam]              0.274    0.202  1.354 0.176 -0.122  0.670
log_d                                -0.300    0.045 -6.598 0.000 -0.389 -0.211
log_d:camera[T.stationary_cam]       -0.093    0.060 -1.541 0.123 -0.211  0.025
Group Var                             0.062    0.067
Group x camera[T.stationary_cam] Cov -0.017    0.040
camera[T.stationary_cam] Var          0.029    0.042
===============================================================================

In [5]:
model_accuracy = smf.mixedlm(
    "accuracy ~ camera",
    data=df[df['block'] != 3],
    groups=df[df['block'] != 3]["participant"],
    re_formula="~camera"
)

result_accuracy = model_accuracy.fit()
print(result_accuracy.summary())

                     Mixed Linear Model Regression Results
================================================================================
Model:                    MixedLM         Dependent Variable:         accuracy
No. Observations:         415             Method:                     REML
No. Groups:               30              Scale:                      256.1728
Min. group size:          13              Log-Likelihood:             -1786.4536
Max. group size:          14              Converged:                  Yes
Mean group size:          13.8
--------------------------------------------------------------------------------
                                      Coef.  Std.Err.   z    P>|z| [0.025 0.975]
--------------------------------------------------------------------------------
Intercept                             45.948    3.242 14.171 0.000 39.593 52.303
camera[T.stationary_cam]               0.895    2.158  0.415 0.678 -3.334  5.125
Group Var                            278.417    5.381
Group x camera[T.stationary_cam] Cov   2.137    2.474
camera[T.stationary_cam] Var          65.527    2.392
================================================================================

In [6]:
model_efficiency = smf.mixedlm(
    "efficiency ~ camera",
    data=df[df['block'] != 3],
    groups=df[df['block'] != 3]["participant"],
    re_formula="~camera"
)

result_efficiency = model_efficiency.fit()
print(result_efficiency.summary())

                     Mixed Linear Model Regression Results
================================================================================
Model:                    MixedLM         Dependent Variable:         efficiency
No. Observations:         415             Method:                     REML
No. Groups:               30              Scale:                      237.2208
Min. group size:          13              Log-Likelihood:             -1767.7539
Max. group size:          14              Converged:                  Yes
Mean group size:          13.8
--------------------------------------------------------------------------------
                                      Coef.  Std.Err.   z    P>|z| [0.025 0.975]
--------------------------------------------------------------------------------
Intercept                             43.803    3.179 13.778 0.000 37.572 50.034
camera[T.stationary_cam]               5.513    1.924  2.865 0.004  1.742  9.284
Group Var                            268.989    5.371
Group x camera[T.stationary_cam] Cov -24.458    2.342
camera[T.stationary_cam] Var          42.378    1.968
================================================================================

In [7]:
model_learning_accuracy = smf.mixedlm(
    "accuracy ~ camera * shape_trial_idx",
    data=df,
    groups=df["participant"],
    re_formula="~shape_trial_idx + camera"
)

result_learning_accuracy = model_learning_accuracy.fit()
print(result_learning_accuracy.summary())

                          Mixed Linear Model Regression Results
==========================================================================================
Model:                        MixedLM            Dependent Variable:            accuracy
No. Observations:             830                Method:                        REML
No. Groups:                   30                 Scale:                         261.5753
Min. group size:              26                 Log-Likelihood:                -3551.7547
Max. group size:              28                 Converged:                     Yes
Mean group size:              27.7
------------------------------------------------------------------------------------------
                                                Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------
Intercept                                       43.885    3.833 11.450 0.000 36.373 51.396
camera[T.stationary_cam]                         0.144    3.719  0.039 0.969 -7.145  7.433
shape_trial_idx                                  1.720    1.210  1.421 0.155 -0.652  4.092
camera[T.stationary_cam]:shape_trial_idx         0.099    1.546  0.064 0.949 -2.931  3.130
Group Var                                      276.739    5.768
Group x camera[T.stationary_cam] Cov            20.183    2.545
camera[T.stationary_cam] Var                    78.888    2.431
Group x shape_trial_idx Cov                     -5.349    0.905
camera[T.stationary_cam] x shape_trial_idx Cov -14.893    0.555
shape_trial_idx Var                              6.660    0.265
==========================================================================================

In [8]:
model_learning_efficiency = smf.mixedlm(
    "efficiency ~ camera * shape_trial_idx",
    data=df,
    groups=df["participant"],
    re_formula="~shape_trial_idx + camera"
)

result_learning_efficiency = model_learning_efficiency.fit()
print(result_learning_efficiency.summary())

                          Mixed Linear Model Regression Results
==========================================================================================
Model:                        MixedLM            Dependent Variable:            efficiency
No. Observations:             830                Method:                        REML
No. Groups:                   30                 Scale:                         219.5296
Min. group size:              26                 Log-Likelihood:                -3476.4644
Max. group size:              28                 Converged:                     Yes
Mean group size:              27.7
------------------------------------------------------------------------------------------
                                                Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------
Intercept                                       36.726    3.674  9.995 0.000 29.524 43.927
camera[T.stationary_cam]                         8.431    3.392  2.485 0.013  1.782 15.080
shape_trial_idx                                  4.535    1.242  3.652 0.000  2.101  6.968
camera[T.stationary_cam]:shape_trial_idx        -2.039    1.645 -1.239 0.215 -5.263  1.185
Group Var                                      255.886    5.645
Group x camera[T.stationary_cam] Cov           -10.813    1.905
camera[T.stationary_cam] Var                     1.507    1.153
Group x shape_trial_idx Cov                     -3.054    0.994
camera[T.stationary_cam] x shape_trial_idx Cov  -3.399    0.396
shape_trial_idx Var                             11.890    0.337
==========================================================================================

/Users/minhbui/anaconda3/envs/thesis/lib/python3.13/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/minhbui/anaconda3/envs/thesis/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2200: ConvergenceWarning: Retrying MixedLM optimization with lbfgs
  warnings.warn(

**OBJECTIVE**

In [9]:
# Trade-off
print("\nEffect of duration on chamfer distance for dynamic cam:")
perform_t_test(result_trade_off, 4, {"log_d": 1})

print("\nEffect of duration on chamfer distance for stationary cam:")
perform_t_test(result_trade_off, 4, {"log_d": 1, "log_d:camera[T.stationary_cam]": 1})

print("\nEffect of duration on chamfer distance by camera:")
perform_t_test(result_trade_off, 4, {"log_d:camera[T.stationary_cam]": 1})

Effect of duration on chamfer distance for dynamic cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.3001      0.045     -6.598      0.000      -0.389      -0.211
==============================================================================

Effect of duration on chamfer distance for stationary cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.3931      0.043     -9.127      0.000      -0.477      -0.309
==============================================================================

Effect of duration on chamfer distance by camera:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.0930      0.060     -1.541      0.123      -0.211       0.025
==============================================================================

In [10]:
# Trade-off correlation
def corr_report(data, x, y, label=""):
    sub = data[[x, y]].dropna()
    n = len(sub)
    if n < 3:
        print(f"{label}{x} vs {y}: not enough data (n={n})")
        return
    r_s, p_s = spearmanr(sub[x], sub[y])
    print(f"{label}{x} vs {y} (n={n})")
    print(f"  rho={r_s:.3f}, p={p_s:.4g}")

agg_cam = (
    df
    .groupby(["participant", "camera"], as_index=False)
    .agg(
        duration_mean=("log_d", "mean"),
        chamfer_mean=("log_c", "mean"),
    )
)

for cam, g in agg_cam.groupby("camera"):
    corr_report(g, "duration_mean", "chamfer_mean", label=f"[{cam}] ")

[dynamic_cam] duration_mean vs chamfer_mean (n=30)
  rho=-0.596, p=0.0005041
[stationary_cam] duration_mean vs chamfer_mean (n=30)
  rho=-0.758, p=1.201e-06

In [11]:
# Performance
print("\nEffect of camera on accuracy:")
perform_t_test(result_accuracy, 2, {"camera[T.stationary_cam]": 1})

print("\nEffect of camera on efficiency:")
perform_t_test(result_efficiency, 2, {"camera[T.stationary_cam]": 1})

Effect of camera on accuracy:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.8952      2.158      0.415      0.678      -3.334       5.125
==============================================================================

Effect of camera on efficiency:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             5.5128      1.924      2.865      0.004       1.742       9.284
==============================================================================

In [12]:
# Performance summary stats
def kde_peak(x):
    kde = gaussian_kde(x)
    xs = np.linspace(x.min(), x.max(), 1000)
    return xs[kde(xs).argmax()]

perf = df[df["block"] != 3]
g = perf.groupby("camera")["accuracy"]
df_summary = g.describe()[["count", "mean", "std", "min", "25%", "50%", "75%", "max"]]

df_summary['kde_peak'] = g.apply(kde_peak)
df_summary['kurtosis_excess'] = g.apply(lambda y: kurtosis(y, fisher=True, bias=False))
df_summary['skewness'] = g.apply(lambda y: skew(y, bias=False))

print("\nSummary statistics for accuracy by camera:")
display(df_summary)


perf = df[df["block"] != 3]
g = perf.groupby("camera")["efficiency"]
df_summary = g.describe()[["count", "mean", "std", "min", "25%", "50%", "75%", "max"]]

df_summary['kde_peak'] = g.apply(kde_peak)
df_summary['kurtosis_excess'] = g.apply(lambda y: kurtosis(y, fisher=True, bias=False))
df_summary['skewness'] = g.apply(lambda y: skew(y, bias=False))

print("\nSummary statistics for efficiency by camera:")
display(df_summary)

Summary statistics for accuracy by camera:

,count,mean,std,min,25%,50%,75%,max,kde_peak,kurtosis_excess,skewness
camera,,,,,,,,,,,
dynamic_cam,208.0,45.789845,22.722172,2.286994,31.131259,44.414263,63.046669,91.316218,41.677301,-0.782602,-0.031425
stationary_cam,207.0,47.057188,24.481154,0.278821,26.072135,49.741721,67.139645,94.069261,64.307930,-1.065926,-0.180167

Summary statistics for efficiency by camera:

,count,mean,std,min,25%,50%,75%,max,kde_peak,kurtosis_excess,skewness
camera,,,,,,,,,,,
dynamic_cam,208.0,43.900615,22.444929,2.244370,27.821231,39.292724,61.345837,95.223836,32.213727,-0.809798,0.275702
stationary_cam,207.0,49.170302,21.937543,3.003602,30.669289,49.444986,67.680663,93.846892,47.743240,-0.856544,0.002221

In [13]:
# Learning
print("\nLearning effect on accuracy for dynamic cam:")
perform_t_test(result_learning_accuracy, 4, {"shape_trial_idx": 1})

print("\nLearning effect on accuracy for stationary cam:")
perform_t_test(result_learning_accuracy, 4, {"shape_trial_idx": 1, "camera[T.stationary_cam]:shape_trial_idx": 1})

print("\nLearning effect on accuracy by camera:")
perform_t_test(result_learning_accuracy, 4, {"camera[T.stationary_cam]:shape_trial_idx": 1})

print("\nLearning effect on efficiency for dynamic cam:")
perform_t_test(result_learning_efficiency, 4, {"shape_trial_idx": 1})

print("\nLearning effect on efficiency for stationary cam:")
perform_t_test(result_learning_efficiency, 4, {"shape_trial_idx": 1, "camera[T.stationary_cam]:shape_trial_idx": 1})

print("\nLearning effect on efficiency by camera:")
perform_t_test(result_learning_efficiency, 4, {"camera[T.stationary_cam]:shape_trial_idx": 1})

Learning effect on accuracy for dynamic cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             1.7200      1.210      1.421      0.155      -0.652       4.092
==============================================================================

Learning effect on accuracy for stationary cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             1.8194      0.946      1.923      0.054      -0.035       3.674
==============================================================================

Learning effect on accuracy by camera:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.0994      1.546      0.064      0.949      -2.931       3.130
==============================================================================

Learning effect on efficiency for dynamic cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             4.5346      1.242      3.652      0.000       2.101       6.968
==============================================================================

Learning effect on efficiency for stationary cam:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             2.4959      1.038      2.405      0.016       0.462       4.530
==============================================================================

Learning effect on efficiency by camera:

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -2.0386      1.645     -1.239      0.215      -5.263       1.185
==============================================================================

In [14]:
# Learning summary stats
print("\nSummary statistics for accuracy by camera and shape_trial_idx:")
display(df.groupby(["camera", "shape_trial_idx"])["accuracy"].describe())

print("\nSummary statistics for efficiency by camera and shape_trial_idx:")
df.groupby(["camera", "shape_trial_idx"])["efficiency"].describe()

Summary statistics for accuracy by camera and shape_trial_idx:

                                count       mean        std       min  \
camera         shape_trial_idx
dynamic_cam    1                104.0  44.877342  21.537273  2.286994
               2                104.0  46.702348  23.918010  3.059129
               3                 83.0  56.435467  22.431205  6.609132
               4                 83.0  51.930068  23.124484  3.722271
stationary_cam 1                105.0  44.810623  24.883405  3.763851
               2                102.0  49.369829  23.961758  0.278821
               3                123.0  47.733244  26.240306  0.263833
               4                126.0  49.262318  24.976460  0.399123

                                      25%        50%        75%        max
camera         shape_trial_idx
dynamic_cam    1                32.691314  43.598997  62.772573  85.629202
               2                28.875876  46.555287  63.590301  91.316218
               3                40.153627  58.440341  75.270833  94.697399
               4                34.384813  52.906062  72.220761  89.855950
stationary_cam 1                23.623881  45.885343  66.331181  91.717284
               2                30.765013  54.320892  68.224939  94.069261
               3                26.668058  52.328122  70.110122  90.002149
               4                30.688610  52.540270  71.457548  89.209359

Summary statistics for efficiency by camera and shape_trial_idx:

                                count       mean        std        min  \
camera         shape_trial_idx
dynamic_cam    1                104.0  42.417479  22.832170   2.613109
               2                104.0  45.383752  22.061065   2.244370
               3                 83.0  49.699065  23.144975   3.417138
               4                 83.0  54.973690  24.042102   4.682141
stationary_cam 1                105.0  45.521502  21.042806   3.003602
               2                102.0  52.926420  22.305380   4.240919
               3                123.0  51.515783  23.800922  10.169879
               4                126.0  55.571874  22.822201  11.310082

                                      25%        50%        75%        max
camera         shape_trial_idx
dynamic_cam    1                27.337218  35.926488  59.836582  95.223836
               2                28.878087  45.760154  62.166343  89.198124
               3                29.302344  55.900231  68.255634  88.062914
               4                32.218257  61.367197  73.309268  95.063234
stationary_cam 1                28.640246  44.887467  59.409739  92.319489
               2                32.533442  54.797408  70.296343  93.846892
               3                32.422436  51.652130  70.856130  97.170853
               4                39.148585  56.768210  72.899104  98.467627

In [15]:
# Learning first vs last trial
print("\nLearning effect on accuracy:")
print("\nCamera difference at first trial (t=1):")
perform_t_test(
    result_learning_accuracy,
    4,
    {
        "camera[T.stationary_cam]": 1,
        "camera[T.stationary_cam]:shape_trial_idx": 1
    }
)

print("\nCamera difference at last trial (t=4):")
perform_t_test(
    result_learning_accuracy,
    4,
    {
        "camera[T.stationary_cam]": 1,
        "camera[T.stationary_cam]:shape_trial_idx": 4
    }
)

print("\nLearning effect on efficiency:")
print("\nCamera difference at first trial (t=1):")
perform_t_test(
    result_learning_efficiency,
    4,
    {
        "camera[T.stationary_cam]": 1,
        "camera[T.stationary_cam]:shape_trial_idx": 1
    }
)

print("\nCamera difference at last trial (t=4):")
perform_t_test(
    result_learning_efficiency,
    4,
    {
        "camera[T.stationary_cam]": 1,
        "camera[T.stationary_cam]:shape_trial_idx": 4
    }
)

Learning effect on accuracy:

Camera difference at first trial (t=1):

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.2431      2.622      0.093      0.926      -4.895       5.381
==============================================================================

Camera difference at last trial (t=4):

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.5413      3.833      0.141      0.888      -6.971       8.054
==============================================================================

Learning effect on efficiency:

Camera difference at first trial (t=1):

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             6.3923      2.000      3.195      0.001       2.471      10.313
==============================================================================

Camera difference at last trial (t=4):

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.2764      3.735      0.074      0.941      -7.044       7.597
==============================================================================

**SUBJECTIVE**

*Questionnaire*

In [16]:
category_scores = (
    df_questionnaire
    .groupby(["participant", "camera", "category"])["Response"]
    .mean()
    .reset_index()
)

pivot = category_scores.pivot_table(
    index=["participant", "category"],
    columns="camera",
    values="Response"
).reset_index()

for cat in pivot["category"].unique():
    subset = pivot[pivot["category"] == cat]
    
    stat, p = wilcoxon(subset["stationary_cam"], subset["dynamic_cam"], alternative='greater')
    
    print(f"{cat}: n={len(subset)}, p-value = {p:.4f}")

camera usability: n=30, p-value = 0.3121
physical discomfort: n=30, p-value = 0.1904
robot control: n=30, p-value = 0.6118
system latency: n=30, p-value = 0.0446
task accuracy: n=30, p-value = 0.2605

In [17]:
df_questionnaire.groupby(["camera", "category"])['Response'].describe()

                                    count      mean       std  min   25%  50%  \
camera         category
dynamic_cam    camera usability     150.0  3.333333  1.196565  1.0  2.00  4.0
               physical discomfort  150.0  4.506667  0.967573  2.0  4.00  5.0
               robot control         60.0  3.866667  0.982330  2.0  4.00  4.0
               system latency        60.0  4.000000  1.164445  2.0  3.00  4.0
               task accuracy         90.0  3.677778  1.178723  1.0  2.25  4.0
stationary_cam camera usability     150.0  3.473333  1.272827  1.0  2.00  4.0
               physical discomfort  150.0  4.653333  0.882238  1.0  5.00  5.0
               robot control         60.0  3.850000  1.022211  2.0  3.00  4.0
               system latency        60.0  4.316667  0.929583  2.0  4.00  5.0
               task accuracy         90.0  3.722222  1.190107  1.0  3.00  4.0

                                     75%  max
camera         category
dynamic_cam    camera usability     4.00  5.0
               physical discomfort  5.00  5.0
               robot control        4.25  5.0
               system latency       5.00  5.0
               task accuracy        5.00  5.0
stationary_cam camera usability     5.00  5.0
               physical discomfort  5.00  5.0
               robot control        5.00  5.0
               system latency       5.00  5.0
               task accuracy        5.00  5.0

In [18]:
category_scores = (
    df_questionnaire
    .groupby(["participant", "camera", "Question"])["Response"]
    .mean()
    .reset_index()
)

pivot = category_scores.pivot_table(
    index=["participant", "Question"],
    columns="camera",
    values="Response"
).reset_index()

for question in pivot["Question"].unique():
    subset = pivot[pivot["Question"] == question]
    
    stat, p = wilcoxon(subset["stationary_cam"], subset["dynamic_cam"], alternative='greater')
    
    print(f"{question}: p-value = {p:.4f}")

I felt disoriented during the experiment.: p-value = 0.1360
I felt dizzy during the experiment.: p-value = 0.0422
I felt fatigued during the experiment.: p-value = 0.3968
I felt like I was going to vomit during the experiment.: p-value = 0.0416
I felt sick to my stomach during the experiment.: p-value = 0.0899
I felt that I could have performed better with a different camera perspective.: p-value = 0.8137
I felt that I had good control over the robot during the experiment.: p-value = 0.2397
I felt that the camera perspective provided a good view of the workspace.: p-value = 0.8911
I felt that the latency affected my performance during the experiment.: p-value = 0.1405
I felt that the robot responded well to my commands during the experiment.: p-value = 0.7941
I felt that the shapes were too difficult to follow during the experiment.: p-value = 0.6371
I felt that there was a delay between my commands and the robot's response during the experiment.: p-value = 0.0134
I looked at the whole shape before trying to follow it during the experiment.: p-value = 0.2154
I was able to accurately perform the tasks during the experiment.: p-value = 0.3735
It did not take long to get used to this camera perspective.: p-value = 0.0258
It was easy to use this camera perspective.: p-value = 0.0441
Overall, I am satisfied with this camera perspective.: p-value = 0.2293

In [19]:
df_questionnaire.groupby(["camera", "Question"])['Response'].describe()

                                                                   count  \
camera         Question
dynamic_cam    I felt disoriented during the experiment.            30.0
               I felt dizzy during the experiment.                  30.0
               I felt fatigued during the experiment.               30.0
               I felt like I was going to vomit during the exp...   30.0
               I felt sick to my stomach during the experiment.     30.0
               I felt that I could have performed better with ...   30.0
               I felt that I had good control over the robot d...   30.0
               I felt that the camera perspective provided a g...   30.0
               I felt that the latency affected my performance...   30.0
               I felt that the robot responded well to my comm...   30.0
               I felt that the shapes were too difficult to fo...   30.0
               I felt that there was a delay between my comman...   30.0
               I looked at the whole shape before trying to fo...   30.0
               I was able to accurately perform the tasks duri...   30.0
               It did not take long to get used to this camera...   30.0
               It was easy to use this camera perspective.          30.0
               Overall, I am satisfied with this camera perspe...   30.0
stationary_cam I felt disoriented during the experiment.            30.0
               I felt dizzy during the experiment.                  30.0
               I felt fatigued during the experiment.               30.0
               I felt like I was going to vomit during the exp...   30.0
               I felt sick to my stomach during the experiment.     30.0
               I felt that I could have performed better with ...   30.0
               I felt that I had good control over the robot d...   30.0
               I felt that the camera perspective provided a g...   30.0
               I felt that the latency affected my performance...   30.0
               I felt that the robot responded well to my comm...   30.0
               I felt that the shapes were too difficult to fo...   30.0
               I felt that there was a delay between my comman...   30.0
               I looked at the whole shape before trying to fo...   30.0
               I was able to accurately perform the tasks duri...   30.0
               It did not take long to get used to this camera...   30.0
               It was easy to use this camera perspective.          30.0
               Overall, I am satisfied with this camera perspe...   30.0

                                                                       mean  \
camera         Question
dynamic_cam    I felt disoriented during the experiment.           4.200000
               I felt dizzy during the experiment.                 4.433333
               I felt fatigued during the experiment.              4.166667
               I felt like I was going to vomit during the exp...  4.900000
               I felt sick to my stomach during the experiment.    4.833333
               I felt that I could have performed better with ...  2.833333
               I felt that I had good control over the robot d...  3.600000
               I felt that the camera perspective provided a g...  3.600000
               I felt that the latency affected my performance...  4.100000
               I felt that the robot responded well to my comm...  4.133333
               I felt that the shapes were too difficult to fo...  4.033333
               I felt that there was a delay between my comman...  3.900000
               I looked at the whole shape before trying to fo...  4.033333
               I was able to accurately perform the tasks duri...  2.966667
               It did not take long to get used to this camera...  3.600000
               It was easy to use this camera perspective.         3.200000
               Overall, I am satisfied with this camera perspe...  3.433333
stationary_cam I felt disoriented during the experiment.           4.366667
               I felt dizzy during the experiment.                 4.733333
               I felt fatigued during the experiment.              4.200000
               I felt like I was going to vomit during the exp...  5.000000
               I felt sick to my stomach during the experiment.    4.966667
               I felt that I could have performed better with ...  2.700000
               I felt that I had good control over the robot d...  3.700000
               I felt that the camera perspective provided a g...  3.266667
               I felt that the latency affected my performance...  4.300000
               I felt that the robot responded well to my comm...  4.000000
               I felt that the shapes were too difficult to fo...  3.966667
               I felt that there was a delay between my comman...  4.333333
               I looked at the whole shape before trying to fo...  4.166667
               I was able to accurately perform the tasks duri...  3.033333
               It did not take long to get used to this camera...  4.066667
               It was easy to use this camera perspective.         3.700000
               Overall, I am satisfied with this camera perspe...  3.633333

                                                                        std  \
camera         Question
dynamic_cam    I felt disoriented during the experiment.           1.186127
               I felt dizzy during the experiment.                 1.006302
               I felt fatigued during the experiment.              1.205829
               I felt like I was going to vomit during the exp...  0.305129
               I felt sick to my stomach during the experiment.    0.592093
               I felt that I could have performed better with ...  1.116748
               I felt that I had good control over the robot d...  1.101723
               I felt that the camera perspective provided a g...  1.101723
               I felt that the latency affected my performance...  1.155198
               I felt that the robot responded well to my comm...  0.776079
               I felt that the shapes were too difficult to fo...  0.999425
               I felt that there was a delay between my comman...  1.184672
               I looked at the whole shape before trying to fo...  1.217214
               I was able to accurately perform the tasks duri...  0.999425
               It did not take long to get used to this camera...  1.132589
               It was easy to use this camera perspective.         1.297212
               Overall, I am satisfied with this camera perspe...  1.222866
stationary_cam I felt disoriented during the experiment.           1.066200
               I felt dizzy during the experiment.                 0.784915
               I felt fatigued during the experiment.              1.297212
               I felt like I was going to vomit during the exp...  0.000000
               I felt sick to my stomach during the experiment.    0.182574
               I felt that I could have performed better with ...  1.207734
               I felt that I had good control over the robot d...  1.022168
               I felt that the camera perspective provided a g...  1.337350
               I felt that the latency affected my performance...  0.952311
               I felt that the robot responded well to my comm...  1.017095
               I felt that the shapes were too difficult to fo...  1.098065
               I felt that there was a delay between my comman...  0.922266
               I looked at the whole shape before trying to fo...  1.053183
               I was able to accurately perform the tasks duri...  1.129032
               It did not take long to get used to this camera...  1.014833
               It was easy to use this camera perspective.         1.207734
               Overall, I am satisfied with this camera perspe...  1.217214

                                                                   min   25%  \
camera         Question
dynamic_cam    I felt disoriented during the experiment.           2.0  4.00
               I felt dizzy during the experiment.                 2.0  4.00
               I felt fatigued during the experiment.              2.0  4.00
               I felt like I was going to vomit during the exp...  4.0  5.00
               I felt sick to my stomach during the experiment.    2.0  5.00
               I felt that I could have performed better with ...  1.0  2.00
               I felt that I had good control over the robot d...  2.0  2.25
               I felt that the camera perspective provided a g...  1.0  3.00
               I felt that the latency affected my performance...  2.0  3.25
               I felt that the robot responded well to my comm...  2.0  4.00
               I felt that the shapes were too difficult to fo...  2.0  4.00
               I felt that there was a delay between my comman...  2.0  3.00
               I looked at the whole shape before trying to fo...  1.0  4.00
               I was able to accurately perform the tasks duri...  1.0  2.00
               It did not take long to get used to this camera...  2.0  2.25
               It was easy to use this camera perspective.         1.0  2.00
               Overall, I am satisfied with this camera perspe...  1.0  2.00
stationary_cam I felt disoriented during the experiment.           1.0  4.00
               I felt dizzy during the experiment.                 2.0  5.00
               I felt fatigued during the experiment.              1.0  4.00
               I felt like I was going to vomit during the exp...  5.0  5.00
               I felt sick to my stomach during the experiment.    4.0  5.00
               I felt that I could have performed better with ...  1.0  2.00
               I felt that I had good control over the robot d...  2.0  3.00
               I felt that the camera perspective provided a g...  1.0  2.00
               I felt that the latency affected my performance...  2.0  4.00
               I felt that the robot responded well to my comm...  2.0  4.00
               I felt that the shapes were too difficult to fo...  1.0  4.00
               I felt that there was a delay between my comman...  2.0  4.00
               I looked at the whole shape before trying to fo...  1.0  4.00
               I was able to accurately perform the tasks duri...  1.0  2.00
               It did not take long to get used to this camera...  2.0  4.00
               It was easy to use this camera perspective.         1.0  3.00
               Overall, I am satisfied with this camera perspe...  1.0  2.25

                                                                   50%   75%  \
camera         Question
dynamic_cam    I felt disoriented during the experiment.           5.0  5.00
               I felt dizzy during the experiment.                 5.0  5.00
               I felt fatigued during the experiment.              5.0  5.00
               I felt like I was going to vomit during the exp...  5.0  5.00
               I felt sick to my stomach during the experiment.    5.0  5.00
               I felt that I could have performed better with ...  3.0  4.00
               I felt that I had good control over the robot d...  4.0  4.00
               I felt that the camera perspective provided a g...  4.0  4.00
               I felt that the latency affected my performance...  5.0  5.00
               I felt that the robot responded well to my comm...  4.0  5.00
               I felt that the shapes were too difficult to fo...  4.0  5.00
               I felt that there was a delay between my comman...  4.0  5.00
               I looked at the whole shape before trying to fo...  4.0  5.00
               I was able to accurately perform the tasks duri...  3.0  4.00
               It did not take long to get used to this camera...  4.0  4.00
               It was easy to use this camera perspective.         3.0  4.00
               Overall, I am satisfied with this camera perspe...  4.0  4.00
stationary_cam I felt disoriented during the experiment.           5.0  5.00
               I felt dizzy during the experiment.                 5.0  5.00
               I felt fatigued during the experiment.              5.0  5.00
               I felt like I was going to vomit during the exp...  5.0  5.00
               I felt sick to my stomach during the experiment.    5.0  5.00
               I felt that I could have performed better with ...  2.0  4.00
               I felt that I had good control over the robot d...  4.0  4.00
               I felt that the camera perspective provided a g...  3.5  4.00
               I felt that the latency affected my performance...  5.0  5.00
               I felt that the robot responded well to my comm...  4.0  5.00
               I felt that the shapes were too difficult to fo...  4.0  5.00
               I felt that there was a delay between my comman...  5.0  5.00
               I looked at the whole shape before trying to fo...  4.0  5.00
               I was able to accurately perform the tasks duri...  3.5  4.00
               It did not take long to get used to this camera...  4.0  5.00
               It was easy to use this camera perspective.         4.0  5.00
               Overall, I am satisfied with this camera perspe...  4.0  4.75

                                                                   max
camera         Question
dynamic_cam    I felt disoriented during the experiment.           5.0
               I felt dizzy during the experiment.                 5.0
               I felt fatigued during the experiment.              5.0
               I felt like I was going to vomit during the exp...  5.0
               I felt sick to my stomach during the experiment.    5.0
               I felt that I could have performed better with ...  5.0
               I felt that I had good control over the robot d...  5.0
               I felt that the camera perspective provided a g...  5.0
               I felt that the latency affected my performance...  5.0
               I felt that the robot responded well to my comm...  5.0
               I felt that the shapes were too difficult to fo...  5.0
               I felt that there was a delay between my comman...  5.0
               I looked at the whole shape before trying to fo...  5.0
               I was able to accurately perform the tasks duri...  4.0
               It did not take long to get used to this camera...  5.0
               It was easy to use this camera perspective.         5.0
               Overall, I am satisfied with this camera perspe...  5.0
stationary_cam I felt disoriented during the experiment.           5.0
               I felt dizzy during the experiment.                 5.0
               I felt fatigued during the experiment.              5.0
               I felt like I was going to vomit during the exp...  5.0
               I felt sick to my stomach during the experiment.    5.0
               I felt that I could have performed better with ...  5.0
               I felt that I had good control over the robot d...  5.0
               I felt that the camera perspective provided a g...  5.0
               I felt that the latency affected my performance...  5.0
               I felt that the robot responded well to my comm...  5.0
               I felt that the shapes were too difficult to fo...  5.0
               I felt that there was a delay between my comman...  5.0
               I looked at the whole shape before trying to fo...  5.0
               I was able to accurately perform the tasks duri...  5.0
               It did not take long to get used to this camera...  5.0
               It was easy to use this camera perspective.         5.0
               Overall, I am satisfied with this camera perspe...  5.0

*Preferences*

In [20]:
print(binomtest(7, 8, p=0.5, alternative='greater'))
binomtest(19, 30, p=0.5, alternative='greater')

BinomTestResult(k=7, n=8, alternative='greater', statistic=0.875, pvalue=0.03515625)

BinomTestResult(k=19, n=30, alternative='greater', statistic=0.6333333333333333, pvalue=0.10024421103298667)

In [21]:
df_preference_general = df_questionnaire_preferences[df_questionnaire_preferences['shape'] == "In General"]
n_total = len(df_preference_general)
n_stationary = (df_preference_general['preferred_camera'] == 'stationary_cam').sum()

result = binomtest(n_stationary, n_total, p=0.5, alternative='greater')
print(f'in general: n={n_total}, stationary={n_stationary}, p-value = {result.pvalue}')

for shape in df_questionnaire_preferences['shape'].unique():
    if shape == "In General":
        continue
    
    subset = df_questionnaire_preferences[df_questionnaire_preferences['shape'] == shape]
    n_total = len(subset)
    n_stationary = (subset['preferred_camera'] == 'stationary_cam').sum()
    
    result = binomtest(n_stationary, n_total, p=0.5, alternative='greater')
    print(f'{shape}: n={n_total}, stationary={n_stationary}, p-value = {result.pvalue}')

in general: n=30, stationary=17, p-value = 0.2923323558643461
circle: n=30, stationary=19, p-value = 0.10024421103298667
square: n=30, stationary=20, p-value = 0.049368573352694525
triangle: n=30, stationary=19, p-value = 0.10024421103298667
heart: n=30, stationary=19, p-value = 0.10024421103298667
star: n=30, stationary=15, p-value = 0.572232224047184
flower: n=30, stationary=17, p-value = 0.2923323558643461
writing: n=30, stationary=20, p-value = 0.049368573352694525

*Questionnaire vs. Preference*

In [22]:
def compute_preferred_nonpreferred(row):
    preferred_score = row["stationary_cam"] if row["preferred_camera"] == "stationary_cam" else row["dynamic_cam"]
    nonpreferred_score = row["dynamic_cam"] if row["preferred_camera"] == "stationary_cam" else row["stationary_cam"]
    return pd.Series({"preferred_score": preferred_score, "nonpreferred_score": nonpreferred_score})

In [23]:
# Preferred vs nonpreferred camera scores
df_questionnaire_sum = df_questionnaire.groupby(["participant", "camera"])["Response"].sum().reset_index()
df_questionnaire_sum = df_questionnaire_sum.pivot_table(index="participant", columns="camera", values="Response")

df_questionnaire_combine = df_questionnaire_sum.merge(
    df_questionnaire_preferences[df_questionnaire_preferences['shape'] == "In General"][["participant", "preferred_camera"]],
    on="participant"
)

df_questionnaire_combine[["preferred_score", "nonpreferred_score"]] = df_questionnaire_combine.apply(compute_preferred_nonpreferred, axis=1)

stat, p = wilcoxon(
    df_questionnaire_combine["preferred_score"],
    df_questionnaire_combine["nonpreferred_score"],
    alternative="greater"   # tests preferred > nonpreferred
)

print("Wilcoxon statistic:", stat)
print("p-value:", p)

preferred = sum(df_questionnaire_combine["preferred_score"] >= df_questionnaire_combine["nonpreferred_score"])
print(f"Number of participants with preferred score greater than or equal to nonpreferred score: {preferred} ({preferred/len(df_questionnaire_combine)*100:.1f}%)")

Wilcoxon statistic: 409.0
p-value: 1.6894620451861192e-05
Number of participants with preferred score greater than or equal to nonpreferred score: 26 (86.7%)

In [24]:
# Preferred vs nonpreferred camera category scores
category_scores = (
    df_questionnaire
    .groupby(["participant", "camera", "category"])["Response"]
    .mean()
    .reset_index()
)

category_pivot = category_scores.pivot_table(
    index=["participant", "category"],
    columns="camera",
    values="Response"
).reset_index()

category_pivot = category_pivot.merge(
    df_questionnaire_preferences[df_questionnaire_preferences['shape'] == "In General"][["participant", "preferred_camera"]],
    on="participant"
)

category_pivot[["preferred_score", "nonpreferred_score"]] = category_pivot.apply(compute_preferred_nonpreferred, axis=1)

for cat in category_pivot["category"].unique():
    subset = category_pivot[category_pivot["category"] == cat]
    
    stat, p = wilcoxon(subset["preferred_score"], subset["nonpreferred_score"], alternative="greater")
    
    preferred = sum(subset["preferred_score"] >= subset["nonpreferred_score"])
    print(f"{cat}: Wilcoxon p-value = {p:.4f}, preferred >= nonpreferred in {preferred}/{len(subset)} participants ({preferred/len(subset)*100:.1f}%)")

camera usability: Wilcoxon p-value = 0.0000, preferred >= nonpreferred in 28/30 participants (93.3%)
physical discomfort: Wilcoxon p-value = 0.1631, preferred >= nonpreferred in 25/30 participants (83.3%)
robot control: Wilcoxon p-value = 0.0186, preferred >= nonpreferred in 24/30 participants (80.0%)
system latency: Wilcoxon p-value = 0.0096, preferred >= nonpreferred in 26/30 participants (86.7%)
task accuracy: Wilcoxon p-value = 0.1368, preferred >= nonpreferred in 22/30 participants (73.3%)

**SUBJECTIVE VS OBJECTIVE**

In [25]:
def compute_preference_summaries(df, df_questionnaire_preferences, metric):
    df_preference_general = (
    df_questionnaire_preferences
    .loc[
        df_questionnaire_preferences['shape'] == 'In General',
        ['participant', 'preferred_camera']
    ]
    .rename(columns={'preferred_camera': 'preferred_camera_general'})
)

    df_preferred_best = df[df['block'] != 3].groupby(['participant', 'camera'])[metric].mean().reset_index()
    df_preferred_best = df_preferred_best.groupby(['participant']).apply(
        lambda x: x.loc[x[metric].idxmax()]
    ).reset_index()

    df_preferred_best = df_preferred_best.merge(df_preference_general, on=['participant'], how='left')
    df_preferred_best['used_preferred_camera'] = df_preferred_best['camera'] == df_preferred_best['preferred_camera_general']

    df_count = df_preferred_best.groupby(['used_preferred_camera', 'preferred_camera_general']).size().reset_index(name='count')
    df_count['total'] = df_count.groupby('preferred_camera_general')['count'].transform('sum')
    df_count['percentage'] = df_count['count'] / df_count['total'] * 100

    return df_count

In [26]:
df_count_eff = compute_preference_summaries(df, df_questionnaire_preferences, "efficiency")
df_count_acc = compute_preference_summaries(df, df_questionnaire_preferences, "accuracy")

print("Preferred camera usage in best-efficiency block/trial:")
for camera in df_count_eff['preferred_camera_general'].unique():
	info = df_count_eff[(df_count_eff['preferred_camera_general'] == camera) & (df_count_eff['used_preferred_camera'] == True)]
	result = binomtest(info['count'].values[0], info['total'].values[0], p=0.5, alternative='greater')
	print(f"{camera.replace('_', ' ').capitalize()}: n={info['total'].values[0]}, matched={info['count'].values[0]}, p-value = {result.pvalue:.4f}")

print("\nPreferred camera usage in best-accuracy block/trial:")
for camera in df_count_acc['preferred_camera_general'].unique():
	info = df_count_acc[(df_count_acc['preferred_camera_general'] == camera) & (df_count_acc['used_preferred_camera'] == True)]
	result = binomtest(info['count'].values[0], info['total'].values[0], p=0.5, alternative='greater')
	print(f"{camera.replace('_', ' ').capitalize()}: n={info['total'].values[0]}, matched={info['count'].values[0]}, p-value = {result.pvalue:.4f}")

Preferred camera usage in best-efficiency block/trial:
Dynamic cam: n=13, matched=3, p-value = 0.9888
Stationary cam: n=17, matched=10, p-value = 0.3145

Preferred camera usage in best-accuracy block/trial:
Dynamic cam: n=13, matched=7, p-value = 0.5000
Stationary cam: n=17, matched=10, p-value = 0.3145

In [27]:
def compute_preference_summaries(df, df_questionnaire_preferences, metric):
    df_preferred_best = df[df['block'] != 3].groupby(['participant', 'shape']).apply(
	lambda x: x.loc[x[metric].idxmax()]
    )
    df_preferred_best = df_preferred_best.merge(df_questionnaire_preferences, on=['participant', 'shape'], how='left')
    df_preferred_best['used_preferred_camera'] = df_preferred_best['camera'] == df_preferred_best['preferred_camera']

    # Aggregate to one match rate per participant
    participant_match = (
        df_preferred_best.groupby(['participant', 'preferred_camera'])['used_preferred_camera']
        .mean()
        .reset_index()
    )

    # Majority-vote: did this participant match more often than not?
    participant_match['matched_majority'] = participant_match['used_preferred_camera'] > 0.5

    return participant_match

In [28]:
participant_match_eff = compute_preference_summaries(df, df_questionnaire_preferences, "efficiency")
participant_match_acc = compute_preference_summaries(df, df_questionnaire_preferences, "accuracy")

print("Preferred camera usage in best-efficiency block/trial (majority-vote):")
for camera in participant_match_eff['preferred_camera'].unique():
    subset = participant_match_eff[participant_match_eff['preferred_camera'] == camera]
    n_matched = subset['matched_majority'].sum()
    n_total = len(subset)
    result = binomtest(n_matched, n_total, p=0.5, alternative='greater')
    print(f"{camera.replace('_', ' ').capitalize()}: n={n_total}, matched={n_matched}, p={result.pvalue:.4f}")

print("\nPreferred camera usage in best-accuracy block/trial (majority-vote):")
for camera in participant_match_acc['preferred_camera'].unique():
    subset = participant_match_acc[participant_match_acc['preferred_camera'] == camera]
    n_matched = subset['matched_majority'].sum()
    n_total = len(subset)
    result = binomtest(n_matched, n_total, p=0.5, alternative='greater')
    print(f"{camera.replace('_', ' ').capitalize()}: n={n_total}, matched={n_matched}, p={result.pvalue:.4f}")

Preferred camera usage in best-efficiency block/trial (majority-vote):
Dynamic cam: n=24, matched=10, p=0.8463
Stationary cam: n=29, matched=18, p=0.1325

Preferred camera usage in best-accuracy block/trial (majority-vote):
Dynamic cam: n=24, matched=15, p=0.1537
Stationary cam: n=29, matched=14, p=0.6445